"""initial schema

Revision ID: ce92a0a40b98
Revises: 
Create Date: 2026-09-10 10:28:48.232471
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ce92a0a40b98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_definitions',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('feature_group', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('formula_reference', sa.Text(), nullable=True),
    sa.Column('availability_rule', sa.Text(), nullable=True),
    sa.Column('sensitivity_class', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('feature_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feature_sets',
    sa.Column('set_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feature_ids', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('set_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('institutions',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('institution_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index('ix_clients_institution', 'clients', ['institution_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('decision_policies',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('eligibility_rules', sa.Text(), nullable=False),
    sa.Column('approve_rule', sa.Text(), nullable=False),
    sa.Column('review_rule', sa.Text(), nullable=False),
    sa.Column('decline_rule', sa.Text(), nullable=False),
    sa.Column('fallback_rule', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index('ix_policies_institution_product', 'decision_policies', ['institution_id', 'product_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('feature_set_id', sa.UUID(), nullable=True),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('artifact_uri', sa.String(length=500), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.set_id'], ),
    sa.PrimaryKeyConstraint('model_version_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_institution', 'users', ['institution_id'], unique=False)
    op.create_table('applications',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('requested_term', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('application_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index('ix_applications_client', 'applications', ['client_id'], unique=False)
    op.create_index('ix_applications_institution', 'applications', ['institution_id'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_audit_created', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_event_type', 'audit_events', ['event_type'], unique=False)
    op.create_index('ix_audit_institution', 'audit_events', ['institution_id'], unique=False)
    op.create_table('calibration_versions',
    sa.Column('calibration_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('validation_metrics', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ),
    sa.PrimaryKeyConstraint('calibration_id')
    )
    op.create_table('consents',
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('consent_id')
    )
    op.create_index('ix_consents_application', 'consents', ['application_id'], unique=False)
    op.create_index('ix_consents_client', 'consents', ['client_id'], unique=False)
    op.create_table('data_lineage',
    sa.Column('lineage_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=True),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('lineage_id')
    )
    op.create_index('ix_lineage_application', 'data_lineage', ['application_id'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('feature_set_id', sa.UUID(), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=20), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.set_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index('ix_snapshots_application', 'feature_snapshots', ['application_id'], unique=False)
    op.create_table('information_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('applicant_status', sa.String(length=50), nullable=False),
    sa.Column('credit_depth', sa.String(length=20), nullable=False),
    sa.Column('financial_depth', sa.String(length=20), nullable=False),
    sa.Column('business_depth', sa.String(length=20), nullable=False),
    sa.Column('relationship_depth', sa.String(length=20), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.Column('information_state', sa.String(length=20), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index('ix_profiles_application', 'information_profiles', ['application_id'], unique=False)
    op.create_table('loan_outcomes',
    sa.Column('outcome_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('outcome_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('days_past_due', sa.Integer(), nullable=False),
    sa.Column('default_status', sa.String(length=20), nullable=False),
    sa.Column('recovery_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    op.create_index('ix_outcomes_application', 'loan_outcomes', ['application_id'], unique=False)
    op.create_table('application_data',
    sa.Column('data_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('consent_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality_status', sa.String(length=20), nullable=False),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.consent_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('data_id')
    )
    op.create_index('ix_app_data_application', 'application_data', ['application_id'], unique=False)
    op.create_index('ix_app_data_source', 'application_data', ['source_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('pd_raw', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('pd_calibrated', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('calibration_version_id', sa.UUID(), nullable=True),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['calibration_version_id'], ['calibration_versions.calibration_id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['feature_snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('ix_predictions_application', 'predictions', ['application_id'], unique=False)
    op.create_table('uncertainty_assessments',
    sa.Column('uncertainty_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('factors_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('uncertainty_id')
    )
    op.create_table('decisions',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('uncertainty_id', sa.UUID(), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('final_decision', sa.String(length=20), nullable=True),
    sa.Column('proposed_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('proposed_term', sa.Integer(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['decision_policies.policy_id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.ForeignKeyConstraint(['uncertainty_id'], ['uncertainty_assessments.uncertainty_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index('ix_decisions_application', 'decisions', ['application_id'], unique=False)
    op.create_index('ix_decisions_institution', 'decisions', ['institution_id'], unique=False)
    op.create_table('decision_overrides',
    sa.Column('override_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('original_recommendation', sa.String(length=20), nullable=False),
    sa.Column('final_decision', sa.String(length=20), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ),
    sa.PrimaryKeyConstraint('override_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_reason', sa.String(length=255), nullable=False),
    sa.Column('final_action', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index('ix_reviews_application', 'reviews', ['application_id'], unique=False)
    op.create_index('ix_reviews_status', 'reviews', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_status', table_name='reviews')
    op.drop_index('ix_reviews_application', table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('decision_overrides')
    op.drop_index('ix_decisions_institution', table_name='decisions')
    op.drop_index('ix_decisions_application', table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('uncertainty_assessments')
    op.drop_index('ix_predictions_application', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_app_data_source', table_name='application_data')
    op.drop_index('ix_app_data_application', table_name='application_data')
    op.drop_table('application_data')
    op.drop_index('ix_outcomes_application', table_name='loan_outcomes')
    op.drop_table('loan_outcomes')
    op.drop_index('ix_profiles_application', table_name='information_profiles')
    op.drop_table('information_profiles')
    op.drop_index('ix_snapshots_application', table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index('ix_lineage_application', table_name='data_lineage')
    op.drop_table('data_lineage')
    op.drop_index('ix_consents_client', table_name='consents')
    op.drop_index('ix_consents_application', table_name='consents')
    op.drop_table('consents')
    op.drop_table('calibration_versions')
    op.drop_index('ix_audit_institution', table_name='audit_events')
    op.drop_index('ix_audit_event_type', table_name='audit_events')
    op.drop_index('ix_audit_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_applications_institution', table_name='applications')
    op.drop_index('ix_applications_client', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_users_institution', table_name='users')
    op.drop_table('users')
    op.drop_table('model_versions')
    op.drop_index('ix_policies_institution_product', table_name='decision_policies')
    op.drop_table('decision_policies')
    op.drop_table('data_sources')
    op.drop_index('ix_clients_institution', table_name='clients')
    op.drop_table('clients')
    op.drop_table('institutions')
    op.drop_table('feature_sets')
    op.drop_table('feature_definitions')
    # ### end Alembic commands ###
